# Generated by Django 5.2.8 on 2026-01-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(
                blank=True, max_length=110, null=True, unique=True, verbose_name="Токен"
            ),
        ),
    ]
