# Generated by Django 5.2.8 on 2025-12-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "img",
                    models.ImageField(blank=True, null=True, upload_to="blog/photos"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=False)),
                ("count_views", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "BlogRecord",
                "verbose_name_plural": "BlogRecords",
            },
        ),
    ]
