# Generated by Django 5.2.8 on 2025-12-30 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogrecord",
            options={
                "ordering": ["created_at"],
                "verbose_name": "BlogRecord",
                "verbose_name_plural": "BlogRecords",
            },
        ),
        migrations.RenameField(
            model_name="blogrecord",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="blogrecord",
            old_name="updated",
            new_name="updated_at",
        ),
    ]
