# Generated by Django 5.2.8 on 2025-12-30 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogrecord_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogrecord",
            old_name="img",
            new_name="preview",
        ),
    ]
