# Generated by Django 5.2.8 on 2025-12-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_img_blogrecord_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogrecord",
            name="count_views",
            field=models.IntegerField(default=0, verbose_name="Количество просмотров"),
        ),
        migrations.AlterField(
            model_name="blogrecord",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="blogrecord",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="blogrecord",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Публикуется"),
        ),
        migrations.AlterField(
            model_name="blogrecord",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog/photos", verbose_name="Превью"
            ),
        ),
        migrations.AlterField(
            model_name="blogrecord",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="blogrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
        ),
    ]
